version: '3.8'

services:
  waha:
    image: devlikeapro/waha:latest
    container_name: wpp_bot_waha
    restart: always
    ports:
      - '3000:3000'

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wpp_bot_api
    restart: always
    ports:
      - '5000:5000'
      
# ngrok:
#   image: wernight/ngrok
#   container_name: wpp_bot_ngrok
#   restart: always
#   depends_on:
#     - api
#   environment:
#     - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
#     - NGROK_PORT=api:5000
